spring.application.name=airbnb-clone

spring.datasource.url=jdbc:postgresql://localhost:5432/airbnb_app_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.hibernate.ddl-auto=update

server.servlet.context-path=/api/v1